resources:
- https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python
- https://pypi.org/project/nest-asyncio/


globals:
  resources:
  - ${ROOT_DIR}/assertions/app.py


tests:
- function: allow_nested_event_loops
  description: Allows asyncio event loop to be nested
  arguments: {}
  assertions:
  - method: assertions.app.assert_equals
    expected: 1
- function: allow_nested_event_loops
  description: Allows asyncio event loop to be nested
  arguments:
    data: null
  assertions:
  - method: assertions.app.assert_equals
    expected: 1
